apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tw249c8yd-nodejs
  janus-idp.io/tekton: tw249c8yd-nodejs
  backstage.io/kubernetes-id: tw249c8yd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tw249c8yd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
