apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tw249c8yd-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tw249c8yd-nodejs 
  name: tw249c8yd-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tw249c8yd-nodejs 
